### ISSUE TITLE
Privacy on Dashcam - Applying models

### ISSUE THREAD

**Issue by punov** [Hivemapper/camera_bridge#4]
Action items:
- Communicate with Silvio and grab the latest models, figure all the post-processing details
- make Tensorflow up and running and start applying the model to test imagery on the camera
- share findings, execution details and results

**Comment by Eduard-Voiculescu** [comment]
Update August 2:
- Validated that models spit out same data between `pytorch` and `tensorflowlite`.
- Interesting difference is that the `tflite` model does not highlight the boxes where the plates are, but debugging the execution of the code, shows the proper values are _matched_ with the same confidence as the `pytorch` model. This would most likely be due to a bug/issue on the Yolov8 export.
- Working on running the model (`tflite` for the moment to see if it works as expected) on the raspberry pi

**Comment by Eduard-Voiculescu** [comment]
Update August 3:
- Good progress, I was able to run a google detect.tflite model on the cam and able to match a couple of objects
- Playing around with the `privacy7000_tflite` model to make it work

**Comment by Eduard-Voiculescu** [comment]
Update August 4: 
- Was able to make the `privacy7000_tflite` model work
- The model is _able_ to match boxes on the images but there is no drawing on the resulting images

**Comment by Eduard-Voiculescu** [comment]
Update August 7:
- Still trying to fiddle with the model to have the model return the same output as the yolov8(model) but nothing conclusive as of now
- Will now try to run the pytorch model on the cam to remove the fact that the model was exported from pt -> tflite and eliminate the use-case that the model is faulty for some reason

**Comment by Eduard-Voiculescu** [comment]
Update August 8:
- tried reconverting pytorch `private7000.pt` (to make sure that the issue was not related to the conversion of the model
    - got a different size in bytes and different model
    - the images produces with the model have weird detection of 1 face and 1 plate, this however occurs REGARDLESS of the image, a black image with nothing on it produces the same boxes output as an image with a person and a plate
- will try running the model (latest shared by Alexei) with pytorch on the cam directly

**Comment by Eduard-Voiculescu** [comment]
Update August 9:
- trying to run the yolov5 python code on the raspberry pi and make it listen to the pic directory to where the camera-bridge takes images and stores
