### ISSUE TITLE
USB: Store images in directories based on date.

### ISSUE THREAD

**Issue by mazar-farran** [Hivemapper/camera_bridge#8]
When transferring to USB, instead of storing images in

`{USB}/{filename}.jpg
`

store them in

`{USB}/{YYYY-MM-DD}/{filename}.jpg
`

PR: https://github.com/Hivemapper/camera_bridge/pull/10

**Comment by Masaya-RT** [comment]
@mazar-farran 
1. Is this HDC-only, or both?
2. Is this in a current release, or is this going to be released alongside your other USB work?

**Comment by mazar-farran** [comment]
Hi @Masaya-RT 

1. This is HDC only
2. This is not in a current release
