### ISSUE TITLE
Decouple USB image transfer from image creation.

### ISSUE THREAD

**Issue by mazar-farran** [Hivemapper/camera_bridge#9]
We write to USB slower than we can generate images (~2fps vs ~10fps).  This means if we wait for USB transfers to complete in sequence, we will only process at ~2fps.

A workaround was made to limit usb transfers to 1 transfer for every 5 images.  https://github.com/Hivemapper/camera_bridge/tree/eab9b8afad5d4e48ae3525346c4246ea269bb970. But ideally we would copy as many images to the USB as we can.

Possible options:
1. Do usb transfers on another thread. Maybe have a queue of files to transfer that the USB worker thread consumes.  But we will still need to drop frames if we're falling behind.
2. Batch usb transfers together. Maybe doing ~5 at once is faster than one at a time.

**Comment by jayalberts** [comment]
Code seems to be working, basic validation. Get ready for PR. 

Validation:
- drive with USB stick

**Comment by jayalberts** [comment]
PR has been merged. Will be in a later build of 3.9.

**Comment by jayalberts** [comment]
USB test passed, double check framekms to know for sure

**Comment by mazar-farran** [comment]
Test drive FrameKM upload failure issue was caused by the LaunchDarkly flag `isNativeUploadingEnabled` being set on the Android version of the app when the app version was >6.15.  This was due to a misconfigured flag rule.  This issue was not related to the USB changes.

**Comment by jayalberts** [comment]
created test build, 3.9.0.
